# Generated by Django 5.2.5 on 2025-08-13 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('approved', 'Approved'), ('denied', 'Denied')], max_length=20)),
                ('insurer_name', models.CharField(max_length=100)),
                ('discharge_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denial_reason', models.CharField(max_length=255)),
                ('cpt_codes', models.CharField(max_length=25)),
                ('claim', models.ForeignKey(db_column='claim_id', on_delete=django.db.models.deletion.CASCADE, to='ErisaRecoveryDevChallenge.claimsmodel')),
            ],
        ),
    ]
