# Generated by Django 5.2.5 on 2025-08-13 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErisaRecoveryDevChallenge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimdetailsmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='claimdetailsmodel',
            name='claim',
            field=models.OneToOneField(db_column='claim_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ErisaRecoveryDevChallenge.claimsmodel'),
        ),
    ]
