# Generated by Django 5.2.5 on 2025-08-13 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErisaRecoveryDevChallenge', '0002_remove_claimdetailsmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdetailsmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='claimdetailsmodel',
            name='claim',
            field=models.ForeignKey(db_column='claim_id', on_delete=django.db.models.deletion.CASCADE, to='ErisaRecoveryDevChallenge.claimsmodel'),
        ),
    ]
