# Generated by Django 5.2.5 on 2025-08-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErisaRecoveryDevChallenge', '0004_remove_claimdetailsmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsmodel',
            name='insurer_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, max_length=20),
        ),
    ]
