# Generated by Django 5.2.5 on 2025-08-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErisaRecoveryDevChallenge', '0005_alter_claimsmodel_insurer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsmodel',
            name='flagged_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimsmodel',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
