# Generated by Django 5.2.5 on 2025-08-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErisaRecoveryDevChallenge', '0006_claimsmodel_flagged_for_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimsmodel',
            old_name='review_note',
            new_name='custom_note',
        ),
        migrations.RenameField(
            model_name='claimsmodel',
            old_name='flagged_for_review',
            new_name='flagged',
        ),
    ]
